name: Event demo 1
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:
  push:
    branches:
      - 'dev-*'
      - 'feat/**'
    paths:
      - '.github/workflows/*'
      

jobs:
  deploy:
    runs-on: ubuntu-slim
    steps:
      - name: Deploy
        run: echo "Deployed!"
    
