name: Second workflow
on: [push,workflow_dispatch]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: python version
        run: python3 -v
      - name: Install python package
        run: python3 -m pip install -r requirements.txt
  
  run:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Run python script
        run: python3 main.py